- id: rye-lint
  name: rye-lint
  description: "Run 'rye lint' for extremely fast Python linting"
  entry: rye lint
  language: python
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"

- id: rye-format
  name: rye-format
  description: "Run 'rye fmt' for extremely fast Python formatting"
  entry: rye fmt
  language: python
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
